### ISSUE TITLE
Support React v15

### ISSUE THREAD

**Issue by incubus8** [reactjs/react-a11y#124] opened 2016-08-27 10:14 UTC
Hi guys,

I am wondering. Is there any plan to support / update the latest React v15?

Thank you.

**Comment by tiemevanveen** [comment] 2016-10-11 10:17
I've got no problem using the latest React v15..

**Comment by gavmck** [comment] 2016-11-24 11:16
If you're getting the same ReactDOM issue I was, you have to pass in ReactDOM as an option.

`a11y(React, { ReactDOM: ReactDOM });`

**Comment by Swaagie** [comment] 2017-01-19 10:08
Works fine with React@15 as far as I can tell. As long as you pass `ReactDOM` like gavmck suggested above. Made small improvement to documentation https://github.com/reactjs/react-a11y/pull/129

**Comment by erin-doyle** [comment] 2017-11-27 12:08
This work around should not be needed anymore and v1.0.0 now fully supports React v16.  Please try upgrading to the latest version.  I'm closing this as I believe the issue is resolved in v1.0.0.  I'll reopen if I hear that's not the case.

**Closed by erin-doyle** 2017-11-27 12:08 UTC
