### ISSUE TITLE
Use of "id" prop everywhere breaks my app

### ISSUE THREAD

**Issue by benknight** [reactjs/react-a11y#128] opened 2016-12-19 18:47 UTC
I discovered I couldn't use react-a11y on my app because it looks like it clones every node, adding an "id" prop, which many of my app's routing components use, thus totally breaking it.  I can also see when looking at my DOM that react-a11y is adding ID to literally every single DOM node which I can imagine could create a lot of problems.

**Comment by erin-doyle** [comment] 2017-03-23 23:15
Bump.  This is causing a problem with another library I'm using that throws PropType warnings when components receive any props that are not expected.  The id is being passed to these components that don't want that as a prop.

**Comment by dragGH102** [comment] 2017-06-13 14:48
same here. it even causes accessibility issues! (as I'm using Semantic UI React which apparently relies on the id to set aria / for attributes on labels)

**Comment by MattMcFarland** [comment] 2017-06-20 19:40
Hey I must be missing something, but I think this is only for development environment and not production?  I do think its a bit gratuitous to override all nodes and apply an ID prop to them, but I think this post is really unclear on whether or not the adding of said ID props are causing the problem or just something noticed and being blamed (post-hoc ergo propter-hoc)

Just to be clear:  I think this is in development or test environments only, as I believe this was to be used only to help point out a11y issues (right? or am I missing something?)  What is actually being "broken" and how do you know it is caused by an ID being added?

**Comment by erin-doyle** [comment] 2017-06-20 20:06
You are correct, it should only be used in development/test environments and not production and the purpose is to point out things during the development cycle.  There are some cases where the adding of the ids is causing issues.  There is a PR outstanding that hopefully removes that behavior but it's still got some things to work out.  Hopefully it can be merged soon and we can close this issue.

**Comment by nickmccurdy** [comment] 2017-08-13 23:43
While my app itself works, the added id fields break all my Jest snapshot tests which assume that extra props aren't being added to my components. Unfortunately this would still be an issue even if we namespaced the id.

**Comment by erin-doyle** [comment] 2017-11-27 12:12
I believe this issue has been resolved in v1.0.0.  Please update to the latest and see if you're still having this issue.  I'm closing this for now but will reopen if I hear that this is not yet resolved.

**Closed by erin-doyle** 2017-11-27 12:12 UTC
