### ISSUE TITLE
Migrate to rackt eslint config

### ISSUE THREAD

**Issue by pwmckenna** [reactjs/react-a11y#98] opened 2015-10-28 03:33 UTC
https://github.com/rackt/eslint-config-rackt contains a starting point that all org repos can build off of. This can be introduced by first using the config and overriding any rules that the repo doesn't comply with, without having to change any of the source. Then for non-controversial rules, PRs can be made to update the source to comply.

Here's the initial PR: https://github.com/rackt/react-a11y/pull/97

**Comment by erin-doyle** [comment] 2017-11-27 12:31
The latest v1.0.0 does have an .eslintrc and all code has been cleaned up of any findings so I believe the issue is now resolved anyway. I'm closing this but feel free to reply if you see any other changes that need to be made.

**Closed by erin-doyle** 2017-11-27 12:31 UTC
